### ISSUE TITLE
Finaliser l'UTAC

### ISSUE THREAD

**Issue by Nanaki** [histovec/histovec-beta#1039]
- [x] Ajouter des codes couleurs sur les résultats des contrôles techniques
- [x] Exposer (à la chaîne devops) les paramètres nécessaires au bon fonctionnement de l'api UTAC
- [x] Réparer et mettre à jour l'api fake UTAC
- [x] Permettre de basculer entre l'api UTAC et l'api fake UTAC
- [x] Afficher ou non les onglets UTAC en fonction de l'éligibilité du véhicule (ne pas afficher si 404 ou 406 de l'UTAC)
- [x] Mettre un message d'erreur sur les onglets UTAC lorsque qu'on a une erreur injustifiée
- [x] Une 401 est renvoyée par le backend pour la requête UTAC lors d'un refresh sur le rapport HistoVec

**Comment by romP44** [comment]
Bonjour,
Par curiosité, est-ce qu'une date de mise en production de l'UTAC est disponible ?
Cordialement,
