### ISSUE TITLE
Exemple rapport -bouton fermer innopérant

### ISSUE THREAD

**Issue by philippeBron** [histovec/histovec-beta#104]
Sur la landing page on peut afficher un exemple de rapport, qui s'affiche correctement.
En revanche, le bouton fermer en bas du rapport ne ferme pas le rapport qui reste affiché à l'écran. Il faut utiliser la croix du bandeau du rapport pour pouvoir le fermer.

**Comment by rhanka** [comment]
Sur beta.datalab.mi (v0.1.1, branche master), ce bug ne semble pas reproductible.
A reproduire avec quelqu'un de l'équipe
