### ISSUE TITLE
App: ajout de heatmap pour l'optimization du parcours usager

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#137]
cf. vue-heatmapjs

**Comment by dlequepeys** [comment]
Apparemment ça permet de faire des heatmaps, mais il faut en plus un outil de training utilisateurs du genre hotjar

**Comment by rhanka** [comment]
on devrait pouvoir suivre les sessions sans cookies et sans recours a l'externalisation des données de nos usagers sur un service privé et payant, d'autant que nous disposons d'outils analytiques (ce n'est pas comme si la navigation dans nos 3 pages principales etait compliquée à suivre)

**Comment by rhanka** [comment]
L'analyse des sessions est déjà implémenté. Le réel besoin de heatmap ne semble plus avéré. A réouvrir ultérieurement en cas de besoin.
