### ISSUE TITLE
Search sur mobile : pas de resultat 

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#173]
une recherche sur mobile ne donne pas de résultat  "Désolé, nous n'avons pas ....."
la même recherche est ok sur PC

**Comment by RitchyP** [comment]
la recherche marcher si on rentre  la plaque et la formule dans le champs plaque, et ne fonctionne pas si on rentre chaque champs dans leurs cases respectives

**Comment by rhanka** [comment]
Richard ?

**Comment by rhanka** [comment]
Pas assez qualifié
