### ISSUE TITLE
Search: ne s'affiche pas sur navigateurs anciens (safari < 10, internet explorer 11)

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#182]

**Comment by rhanka** [comment]
cela semble lié à l'inexistance de la fonction de normalisation sous Safari.

**Comment by rhanka** [comment]
Fonctionne bien sur safari après upgrade vers version 10. 
Les versions jusqu'à 9.x n'ont pas eu de màj depuis 2 ans.
Une mise à jour sera préconisée au moins pendant la phase bêta.

**Comment by clepont** [comment]
support en attente

**Comment by rhanka** [comment]
résolu avec #644 #643

**Comment by rhanka** [comment]
abandon programmé pour ces navigateurs #obsolecence-programmee (devient de plus en plus coûteux à maintenir avec l'ensemble des librairies node)
