### ISSUE TITLE
Report: l'envoi mail ne semble pas fonctionner sur tous les devices

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#185]
Smartphones:
- Safari > 10, Iphone iOS11 : ok
- Chrome, Android 7.1 (wiko) + Inbox : ko (ne transmet que le début de l'url)
Linux:
- Firefox 60 + Thunderbird : ok
- Chromium + Thunderbird : ok

Windows:

**Comment by clepont** [comment]
support en attente

**Comment by rhanka** [comment]
test effectués depuis #640 #641
