### ISSUE TITLE
Home: modifier les cartes process Histovec (identification/génération rapport/partage)

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#201]
- 1 => "Identification du titulaire" + icone = fa-drivers-license-o
- 2 => "Génération du rapport" + icone = fa-search
- 3 => "Partagez avec un acheteur" + icone = fa-send

**Comment by Philjem700** [comment]
modification ok
problème sur dernière carte, le texte proposé est trop long, pour l'instant, afficher "partagez...."
