### ISSUE TITLE
Rapport: reformulation

### ISSUE THREAD

**Issue by philippeBron** [histovec/histovec-beta#219]
Proposition remplacer "En acquérant ce véhicule vous serez le 3ème titulaire" par "Ce véhicule a déjà eu 2 propriétaires, en l'achetant vous serez le 3ème.

**Comment by rhanka** [comment]
sans pinailler, on parlera de titulaire et pas de propriétaire (un garagiste ou concessionnaire est compté comme propriétaire même s'il n'est pas titulaire dans la période de revente du véhicule).
