### ISSUE TITLE
Report: envoi rapport - mettre un indicateur de succes de la copie

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#267]

**Comment by clepont** [comment]
On part sur un flash message?

**Comment by rhanka** [comment]
oui - un message evanescent de type toaster.
regarde avec Philippe T ce qui est le plus standard, il faut juste eviter un popup avec clic.
en booatrap 3 lea toaster ne sont pas standard donc il vaut mieux eviter un truc avec trop de js custom et faire simple et robust
