### ISSUE TITLE
Questionnaire satisfaction

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#287]
- Design (probablement en modal) à faire par Philippe
- Nouvel index à créer (ES)
- Interaction Vue à coder

**Comment by clepont** [comment]
Dans un premier temps déclencher la modal sur le rapport au bout de 1min
Proposer une checkbox "Ne plus afficher" qui permet à l'utilisateur de by passer l'ouverture automatique du modal (pr éviter de reproposer la modal)
