### ISSUE TITLE
Search: Adapter le formulaire pour les plaques FNI

### ISSUE THREAD

**Issue by clepont** [histovec/histovec-beta#312]
- Afficher deux images de  plaques (flat design) ancien et nouveau format en haut du formulaire
- A la sélection d'une image adapter le fieldset carte grise:
  - Pour les fni modifier le placeholder
  - Date du certificat d'immatriculation (adapter l'aide ?)
  - Ajouter un flag dans le store pour la recherche FNI et la transmettre dans l'api avec &fni

**Comment by clepont** [comment]
En attente data

**Comment by rhanka** [comment]
intégration en mode oeuf de pâques en attendant la validation
testé pour bon fonctionnement à ce stade sur beta
