### ISSUE TITLE
Historique des dossiers convertis FNI: nombre de calcul de titulaires

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#321]

**Comment by rhanka** [comment]
Le nombre de titulaires est à revérifier avec l'apparition de l'historique FNI (avant 2009)

**Comment by clepont** [comment]
J'ai vérifié l'échantillon présent dans le fichier, pas d'anomalies détéctées

**Comment by rhanka** [comment]
Les données FNI converties ayant été vériées conformes au SIV, il ne semble plus y avoir de problème ou à la marge.
