### ISSUE TITLE
Report: mention "Le nombre de titulaire ne peut etre calculé... " pour immat avant 2009 à supprimer ?

### ISSUE THREAD

**Issue by clepont** [histovec/histovec-beta#334]
Puisque finalement nous remontons déjà l'historique des opérations avant 2009 pour les véhicules convertis. Peut on supprimer le message?  
Voir exemple Ligne 240

**Comment by rhanka** [comment]
240 annulé et Dupuis n'existent pas dans la liste de test commune, recherche d'un autre cas de test
