### ISSUE TITLE
Erreur de Calcul du nombre de sinistre 

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#335]
Dans la synthèse : indication "plusieurs sinistres" dernier déclaré en 2016
Dans l'historique : 
24/02/2016 Procédure de réparation contrôlée
24/02/2016 Premier rapport d'expert
18/03/2016 Opposition dans le cadre de la procédure de réparation contrôlée
15/04/2016 Second rapport d'expert
15/04/2016 Levée d'une opposition véhicule endommagé

L'opposition est une conséquence de la procédure de réparation et pas une procédure supplémentaire.
* voir mail d'Adrien

**Comment by rhanka** [comment]
attente d'envoi du mail

**Comment by rhanka** [comment]
réouverture du bug #200 pour mieux capitaliser sur l'ensemble des cas
