### ISSUE TITLE
API histovec ?

### ISSUE THREAD

**Issue by BenjaminSchmitt** [histovec/histovec-beta#336]
Bonjour,

Est-ce qu'à terme, une API histovec sera exposée et une documentation proposée ?
Peut-on à ce stade appeler simplement l'API sans passer par l'interface ?

Merci.

**Comment by rhanka** [comment]
Bonjour,

Merci beaucoup pour votre interrogation.

A ce stade l'API ne sera pas ouverte, dans la mesure où le cadre légal ne permet pas à un tiers d'interroger l'historique du véhicule d'un titulaire à partir de ses données personnelles.
Le cadre de protection des données personnelles s'applique donc, au titre pénal du terme, à ce stade.
De ce fait, nous ne souhaitons pas documenter dans un premier temps l'API.
Par ailleurs les blocages techniques ne permettent pas une interrogation opérationnelle en tant que "pro" (fréquence d'interrogation bridée).

Cependant l'équipe est ouverte à recueillir les besoins de professionnels, afin de comprendre les niveaux de partenariats à mettre en place. Ces "partenariats" correspondront in fine à des agrément, dont le cadre légale définitif ne saurait être mis en place avant au moins un an.

N'hésitez pas à écrire directement à histovec@interieur.gouv.fr en tant que professionnel si cette interrogation se pose dans un contexte pro.

Bien cordialement,

FA

**Comment by rhanka** [comment]
Aucune API publique n'est planifiée à ce jour, les API partenaires nécessiteraient la mise en place d'un cadre juridique approprié. Le cadre de sollicitation du ministère par des professionnel n'est pas le canal github, mais une sollicitation directe du bureau des immatriculations de la sécurité routière.

**Comment by marccabeza** [comment]
Bonjour Fabien,

Je me permets de relancer ce fil de discussion. J'ai vu que Carizy était en partenariat avec Histovec donc je me suis dit que l'API avait peut-être été ouverte aux professionnels.

Si cela n'est toujours pas ouvert, existe-t-il une solution pour obtenir des informations uniquement sur la situation administrative d'un véhicule sans passer par les données personnelles du propriétaire ?

Merci à vous,

Cordialement,

Marc

**Comment by marccabeza** [comment]
Je précise que nous serions preneurs de tout type de format (fichiers plats, web service).

Merci à vous,

Marc

**Comment by pkconcept** [comment]
Effectivement, vu que carizy "indique" ( à voir si dans les fait cela est vrai ... ) qu'ils utilisent histovec, il serait souhaitable que l'api puisse être (sous certaines conditions) accessibles.

Je travaille avec un client qui propose des solutions de gestion dans l'automobile et un accès à ce système serait un plus ...

**Comment by tesshsu** [comment]
Bonjour,
Possible savoir il est exit API histovec ? or la société webservice qui pourrai offer ce service meme si est payant ? merci

**Comment by zakfriend** [comment]
+1

**Comment by Wimmerke** [comment]
Est-ce que c'est possible d'avoir access à l'API de Histovec?

Pour la raison bien précis:
- rechercher nos propres vehicules
- l'état actuel et historique des véhicules
- incl. les signalitiques si applicables

Alors tout à fait en règle avec l'RGPD et dans le but de histovec comme propéitaire.

La question aussi dans la context du support gouvernemental française à servir les citioyens avec leur données entre outre comme: https://api.gouv.fr/

bàv
Wim
