### ISSUE TITLE
Mettre une tempo quand la recherche tourne trop longtemps

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#338]
Quand le rapport ne peux pas être déchiffré mettre un message du style votre version de navigateur est trop ancienne pour pour utiliser notre service !!

**Comment by rhanka** [comment]
Trop fourre-tout : 
- le bug du déchiffrement est déjà catché (#318, corrigé dans #339 ), 
- et la version ancienne (#182 #199) sont complexe
- implémenter une logique de timeout dans la procédure d'attente actuelle risque d'engendrer à ce stade davantage de dysfonctionnements.

**Comment by rhanka** [comment]
@RitchyP au-delà des problèmes de navigateur, y-a-t-il encore ce type de remontée ?
Sinon je propose de basculer à une priorité basse ?

**Comment by rhanka** [comment]
En attente d'un outil de test sur browser "obsolètes"
