### ISSUE TITLE
Indication importé signalé mais fausse

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#406]
Dans synthèse et historique indication erroné de "véhicule importé" les données sont à import: "NON"
histovec version 0.1.8rc-13-g5e4bfbc

**Comment by rhanka** [comment]
Il a été statué en juin que lors qu'un véhicule a une première immatriculation antérieure à la première immatriculation d'un véhicule d'occasion, il s'agit d'un véhicule importé et qu'il y a un problème de référence de donnée de la table import.
Si cette règle doit être changée, il faut clarifier la spécification pour l'ensemble des cas d'usage et écrire.

**Comment by rhanka** [comment]
Est validé : 
- la première immat d'un véhicule d'occasion ne témoigne majoritairement pas d'un import, le traitement doit être désactivté
- la première immatriculation le cas échéant doit être basculée dans l'historique des opérations en France

**Comment by rhanka** [comment]
Cas positif non présent dans jeu de tests : 
- import =  'NON'
- date_premiere_immat: "01/01/1995"
- date_premiere_immat_siv: "06/08/2013"
- dos_date_conversion_siv: undefined
- historique: 
  - {opa_date: "2013-08-06", opa_type: "IMMAT_NORMALE_PREM_VO"}
  - {opa_date: "2013-08-06", opa_type: "CONVERSION_DOSSIER_FNI"}

Contre exemple (fni converti, avec une "IMMAT_NORMALE" en première op) : ligne 395

**Comment by rhanka** [comment]
développé, à qualifier puis clore

**Comment by rhanka** [comment]
premier niveau de validation ok, sera rouvert si pb
