### ISSUE TITLE
FNI - data : bug véhicule saisi

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#426]
véhicule IVT 34 - dcb3
Le véhicule n'est pas mentionné comme saisi dans les data

**Comment by Adrifrum** [comment]
Erreur liée au SIV.

**Comment by rhanka** [comment]
Non traitable faute de données connexe. Une mention est a publier dans la faq sut les garanties apportées.

**Comment by rhanka** [comment]
Pas de bug applicatif : une limitation sur la qualité des données FNI sera reportée dans la FAQ
