### ISSUE TITLE
CSA: le rapport pdf ne s'ouvre pas au premier clic d'une session

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#453]
Le bouton imprimer csa ne répond pas lors du premier appel.
cela semble le cas lors d'une première utilisation dans une session. Ok au deuxième appuis
et ok tout le long de la session.

**Comment by rhanka** [comment]
Semble avoir été corrigé, à confirmer

**Comment by rhanka** [comment]
Difficile à qualifier à ce stade (0 warning sur les environnements posant problème), semble dépendre des environnement.
Un premier patch (utilisation de @click plutôt que v-on:click) a été utilisé. 
Néanmoins, le problème ne semble pas être javascript et pourrait être sur le caractère clickable du bouton (css) : lorsque le bug se reproduit, en effet le bouton ne change pas de couleur, comme censé le faire lorsque l'on clique.

**Comment by rhanka** [comment]
bon - toujours pas !

**Comment by rhanka** [comment]
Le bug est très probablement lié à l'utilisation de img.onload en deux appels consécutif.
