### ISSUE TITLE
CSA: ajouter la date de premiere immatriculation 

### ISSUE THREAD

**Issue by clepont** [histovec/histovec-beta#469]
Tenir compte de la date:
- En France
- A l'étranger
- Source incertaine

**Comment by rhanka** [comment]
Les sources "étranger", "source incertaine" sont des compléments explicatifs composites de l'application histovec. Le rapport doit être basé sur des informations brutes siv, comme le certificat existant ANTS. Ainsi on ne peut prendre que les informations de première immatriculation.
