### ISSUE TITLE
CSA: Mettre procédure de réparation controlé à OUI 

### ISSUE THREAD

**Issue by clepont** [histovec/histovec-beta#494]

**Comment by clepont** [comment]
En cas de suspension

**Comment by rhanka** [comment]
attente màd des données

**Comment by RitchyP** [comment]
Dans le CSA il faut aussi penser à mettre à OUI opposition ou suspension suivant le cas

**Comment by rhanka** [comment]
dev à venir à partir de jeudi

**Comment by rhanka** [comment]
data dispo, dev en cours
