### ISSUE TITLE
Rapport-synthèse stipuler VEHICULE DE COLLECTION

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#514]
Enrichissement du rapport stipuler "VEHICULE DE COLLECTION" , Attention de ce fait la mention "Eligible Crit'Air" devient non pertinente.  mentions figurant dans les champs Z1 à Z4 du certificat?

**Comment by RitchyP** [comment]
ETU lorsque j’interroge mon véhicule, et que celui-ci est classé collection, j'aimerai que cela apparaisse sur le rapport histovec.
sur l'onglet synthèse:
une icône a déterminer, suivi du texte  `véhicule de collection`
Attention:  la mention "Eligible Crit'Air" devient non pertinente ne devrait pas apparaitre.

**Comment by rhanka** [comment]
Doit on aussi faire apparaître le véhicule de location ?
Pour l'icône, en attente de suggestion.

**Comment by rhanka** [comment]
Seuls véhicules agricoles et de collection sont pris en charge, nouvelle issue à créer si d'autres usages doivent être pris en charge.
```
{
  "COL": {
    "icon": "fa-diamond",
    "text": "véhicule de collection",
    "adv": "Consultez le texte relatif aux véhicules de collection",
    "link": "https://www.service-public.fr/particuliers/vosdroits/F1925"
  },
  "AGR": {
    "icon": "fa-cog",
    "text": "véhicule agricole",
    "adv": "Consultez le texte relatif aux véhicules agricoles",
    "link": "https://www.service-public.fr/professionnels-entreprises/vosdroits/F10522"
  }
}
```
