### ISSUE TITLE
Search rendre le champ 'Plaque d'immatriculation' SIV plus permissif 

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#535]
Pour permettre la saisie de plaque A (x)xx B correspondant à des cyclomoteurs.

ETU, je peux saisir une plaque :

- [ ] AA-XXX-BB
- [ ] A-XXX-BB
- [ ] AA-XXX-B
- [ ] A-XXX-B
- [ ] A-XX-BB
- [ ] AA-XX-B
- [ ] A-XX-B

**Comment by laruiss** [comment]
Est-ce que tu veux bien mettre tous les exemples possibles de plaque ?

**Comment by rhanka** [comment]
proposition d'ergonomie non validée, réouverture du bug
