### ISSUE TITLE
Erreur Inconnu ajouter dans le feedback ID session

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#542]
En cas d'erreur inconnue, ajouter dans le feedback des informations permettant de tracer l'erreur
Id session par exemple.

**Comment by rhanka** [comment]
Le numéro de session est déjà traçé dans les feedback. Il faudrait demander à Rodia de rapporter cette information dans le mail, pour permettre une traçabilité.

**Comment by rhanka** [comment]
#590

**Comment by Rodia-s** [comment]
J'ai regardé la table d'entrée feedback contient bien un id "_id", je ne comprends pas à quoi correspond cette id dans les tables histovec par contre. Je peux le rajouter dans l'email mais j'aimerai être sur qu'il permettra l'identification, sur les id testées je n'ai pas trouvé de correspondance...
