### ISSUE TITLE
Afficher au vendeur un message plus complet lors de CI annulé

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#564]
ETV lorsque j’interroge mon véhicule si le certificat est annulé un message d'erreur apparait  avec ce contenu : 
`Le certificat demandé a été annulé. Une procédure de destruction du véhicule est en cours.`

actuellement le message est :
`Le certificat demandé a été annulé.`

**Comment by rhanka** [comment]
S'agissant d'un simple paramétrage, peux-tu prendre en charge @RitchyP ?
