### ISSUE TITLE
Le QR code du le CSA n'est pas toujours lisible une fois imprimé (trop petit)

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#567]
ETU quand j'imprime le CSA Certificat Administratif Détaillé (onglet Transmettre le rapport)
j'aimerai pouvoir scanner le QR code et consulter l'historique du véhicule sur le site histovec

**Comment by rhanka** [comment]
Je viens de tester en ligne sur un véhicule, ça fonctionne bien. N'est ce pas un pb de lecteur de QR code ? (de mémoire il n'y avait-il pas de pb avec certains lecteurs qui masquent l'url ?)

**Comment by rhanka** [comment]
Impression a tester sur plusieurs modèles

**Comment by RitchyP** [comment]
Je clos cela vient du lecteur pdf pour ma part c'était celui de libre office et il fait un gros patté a la place du QR code c'est OK avec  Foxi-reader
