### ISSUE TITLE
Ajouter une section intitulée " Réseaux sociaux "

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#569]
ETU, sur la page d'accueil. Dans le footer (en gris foncé), à droite de " Un service proposé par ", ajouter une section intitulée " Réseaux sociaux ". Le titre " Réseaux sociaux " est de la même police d'écriture, de la même taille et même couleur que "Un service proposé par ". Le titre est également souligné du même trait dégradé sous " Un service proposé par ".
Sous le titre, positionner les deux logos de Facebook et Twitter 
- Compte Facebook d'Histovec : https://www.facebook.com/Histovec-505863113221188/
- Compte Twitter d'Histovec : https://twitter.com/histovec
Cette évolution requiert de déplacer la section " Un service proposé par " vers la gauche, au centre (pour que ce soit harmonieux). Nous aurions donc, de gauche à droite : " Liens utiles ", " Un service proposé par ", " Réseaux sociaux".

Voir la demande : dans le drive

**Comment by rhanka** [comment]
En attente d'une proposition de maquette boostrap, affectation à @Philjem700

**Comment by rhanka** [comment]
Maquette livrée, en intégration
