### ISSUE TITLE
Evolution rendre la saisie de date de naissance modulable

### ISSUE THREAD

**Issue by RitchyP** [histovec/histovec-beta#593]
En temps que vendeur,  si ma date de naissance n'est composée que d'une année, j'aimerai avoir la possibilité de saisir une date naissance de type par exemple : //1970

**Comment by rhanka** [comment]
travaux data nécessaires, en attente

**Comment by rhanka** [comment]
data dispo

**Comment by rhanka** [comment]
devient inutile du fait de la disparition de la date de naissance, fiable à 65% seulement et donc abandonnée.
