### ISSUE TITLE
frontend: ajout log de consultations des différents éléments du rapport (CSA, etc.)

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#686]

**Comment by rhanka** [comment]
à ajouter :
- le suivi au clic sur différents éléments du rapport (synthèse, historique ...)
- le suivi au téléchargement du csa
- le suivi sur la modalité de partage (copier-coller et mail)

**Comment by Nanaki** [comment]
Closed by commit 93f47ca18bd93e4a0cf3259e77af8ba9dd453d44
