### ISSUE TITLE
Renseigner la page acheteur

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#70]
Pas de texte à ce stade

**Comment by RitchyP** [comment]
ACHETEUR

Vous souhaitez acquérir un véhicule d’occasion, vous avez fait une sélection parmis des annonces, demandez aux vendeurs de partager l'historique de son véhicule.
 
  
HistoVec permet au vendeur de partager à un acheteur intéressé l’historique des faits marquants du véhicule enregistrés dans le fichier national du SIV (Système d’Immatriculation des Véhicules), notamment : 
date de mise en circulation
changements de propriétaire
sinistres à réparation contrôlée
situation administrative (gage, opposition, vol, …)
etc.

en acheteur éclairé, vous pourrez prendre votre décision en toute quiétude.
