### ISSUE TITLE
Ajouter un text mailto sur CONTACT et SIGNALER une erreur

### ISSUE THREAD

**Issue by rhanka** [histovec/histovec-beta#745]
Demande Justine (amélioraton relation usager)

ci-dessous le texte à insérer, dans le mail to CONTACT et SIGNALER UNE ERREUR.

Bonjour,

L'équipe HistoVec nous remercie d'avoir utilisé notre service. Le service HistoVec permet au titulaire du certificat d'immatriculation de transmettre l'historique administratif à un acheteur potentiel et de télécharger le certificat de situation administrative détaillé. Il ne traite pas les questions liées aux démarches de cession, procédures d'immatriculation et certificats d'immatriculation qui sont gérées par l'ANTS (Agence Nationale des Titres Sécurisés).

Pour un usage optimal, nous conseillons l'utilisation de versions récentes de Firefox ou Chrome.

Afin de vous aider plus rapidement dans vos démarches, merci de nous communiquer les informations suivantes :
- Nom :
- Prénom(s) :
- Date de naissance :
- Plaque d'immatriculation :
- Numéro de formule (pour les plaques du type AA-123-AA) ou date du certificat (pour les plaques du type 123 ABC 45) :
- Description du problème :

Bien cordialement,

L'équipe HistoVec.

**Comment by Nanaki** [comment]
@rhanka : quelques suggestions sur le contenu du mail : 

> L'équipe HistoVec nous remercie d'avoir utilisé notre service. Le service HistoVec...
1 - `nous` -> `vous` ?
2 - `notre` ->  `le` ?

Autre proposition :
`Avant toute chose, **nous* vous remercions d'utiliser notre service.` sachant qu'on signe `L'équipe HistoVec` plus bas.

**Comment by Nanaki** [comment]
closed by commit 1d21d76bcd6e0c0d35c0f41cd798f7c724b58b5a
