### ISSUE TITLE
Migrer la fonction feedback vers Monavis (évaluation DINSIC des services publics)

### ISSUE THREAD

**Issue by julien2512** [histovec/histovec-beta#831]
Le cadre est imposé, j'aurai les éléments dans la semaine.

**Comment by rhanka** [comment]
Il y a déjà une fonction de notation lors de l'émission du rapport permettant de suivre l'avis de l'usager titulaire d'un véhicule ou d'un acheteur ayant eu un lien.
L'usager dispose par ailleurs en plus du lien contact pour faire des suggestions

**Comment by julien2512** [comment]
Bonjour,

Certains éléments sont toutefois imposés :

> La DINSIC a souhaité produire un tableau de bord interministériel qui se veut contributif et accessible à tous depuis le site https://monavis.numerique.gouv.fr/. Pour cela, elle a pensé et produit un questionnaire pour recueillir l'avis des usagers à l'issue d'une démarche en ligne (valable pour les démarches dites iconiques dans un premier temps).
> 
> Cette enquête de satisfaction est la même pour tous, 6 questions fermées auxquelles devront répondre les utilisateurs des démarches en ligne.
> 
> Il faut ici définir un calendrier pour l'implémentation du bouton "Mon avis" (avant novembre 2019) et ne pas paralléliser l'enquête avec une fonction de notation "propriétaire".  En clair, nous pouvons réaliser nos propres enquêtes et désactiver le bouton "Mon avis" mais seulement le temps de l'enquête. Nos fonctions de notation sont donc utiles pour améliorer nos services mais ne cadrent pas avec la démarche initiée par la DINSIC.

[Fiche_ Implementation bouton Monavis & Voxusagers.pdf](https://github.com/histovec/histovec-beta/files/3443199/Fiche_.Implementation.bouton.Monavis.Voxusagers.pdf)

**Comment by rhanka** [comment]
Il est imposé dans le texte de ne pas faire de double évaluation.

Pour permettre une transition en douceur, et évaluer l'équivalence des deux échelles (propriétaire HistoVec et Monavis), nous ferons transiter la fonction feedback vers Monavis en mode AB testing sur 1 mois.
